[package]
name = "risc-v-assembler"
version = "0.5.0"
authors = ["pastchick3 <331604390@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
regex = "1.4"
lazy_static = "1.4"
